/* Slash command suggestions and quick search overlay. */
(function () {
  let snippets = [], menu, query = '', token = '';
  const load = () => chrome.runtime.sendMessage({ type: 'GET_SNIPPETS' }, r => { snippets = (r && r.snippets) || []; });
  load(); chrome.runtime.onMessage.addListener(m => { if (m.type === 'SNIPPETS_UPDATED') load(); });
  function ensureMenu() { if (menu) return menu; menu = document.createElement('div'); menu.style.cssText = 'position:fixed;z-index:2147483647;background:#101827;color:#fff;border:1px solid #2a3550;border-radius:12px;box-shadow:0 18px 60px #0008;padding:8px;min-width:260px;font:14px system-ui'; document.documentElement.appendChild(menu); return menu; }
  function matches(q) { q = q.toLowerCase(); return snippets.filter(s => s.shortcut.toLowerCase().startsWith(q) || s.title.toLowerCase().includes(q)).slice(0, 6); }
  async function resolveVars(text) { const names = [...new Set([...text.matchAll(/{{\s*([\w-]+)\s*}}/g)].map(m => m[1]))]; let out = text; for (const n of names) { let v = ''; if (n === 'date') v = new Date().toLocaleDateString(); else if (n === 'time') v = new Date().toLocaleTimeString(); else if (n === 'clipboard') { try { v = await navigator.clipboard.readText(); } catch (_) { v = prompt('Enter clipboard:') || ''; } } else v = prompt(`Enter ${n}:`) || ''; out = out.replace(new RegExp(`{{\\s*${n}\\s*}}`, 'g'), v); } return out; }
  async function use(snippet, replaceLen) { const text = await resolveVars(snippet.content); const result = replaceLen ? window.SlashSnipEngine.replaceBeforeCursor(replaceLen, text) : window.SlashSnipEngine.insertText(text); chrome.runtime.sendMessage({ type: 'USED_SNIPPET', id: snippet.id }); if (!result.ok) { try { await navigator.clipboard.writeText(text); } catch (_) {} alert(`Snippet copied to clipboard. ${result.reason || 'Insertion failed.'}`); chrome.runtime.sendMessage({ type: 'INSERT_FAILED', text, reason: result.reason }); } hide(); }
  function hide(){ if(menu) menu.remove(); menu=null; token=''; }
  function render(items, rect, replaceLen) { const m = ensureMenu(); m.innerHTML = items.map((s,i)=>`<div data-i="${i}" style="padding:10px;border-radius:8px;cursor:pointer;${i?'':'background:#24314d'}"><b>${s.shortcut}</b><br><small>${s.title}</small></div>`).join('') || '<div style="padding:10px;color:#ffcf70">No snippets found</div>'; m.style.left = Math.min(innerWidth-280, Math.max(8, rect.left))+'px'; m.style.top = Math.min(innerHeight-120, rect.bottom+8)+'px'; [...m.querySelectorAll('[data-i]')].forEach(n=>n.onclick=()=>use(items[+n.dataset.i], replaceLen)); }
  function caretRect(){ const el = document.activeElement; const r = el && el.getBoundingClientRect ? el.getBoundingClientRect() : {left:20,bottom:20}; return r; }
  document.addEventListener('keyup', e => { const el = window.SlashSnipEngine.active(); if (!el) return hide(); const val = el.value ?? window.getSelection()?.anchorNode?.textContent ?? ''; const pos = el.selectionStart ?? val.length; const pre = val.slice(0,pos); const m = pre.match(/(^|\s)(\/[\w-]{1,30})$/); if (!m) return hide(); token = m[2]; render(matches(token), caretRect(), token.length); }, true);
  document.addEventListener('keydown', e => { if (menu && (e.key === 'Tab' || e.key === 'Enter')) { const first = matches(token)[0]; if (first) { e.preventDefault(); use(first, token.length); } } if (e.key === 'Escape') hide(); }, true);
  window.SlashSnipQuickSearch = function(){ query=''; render(snippets.slice(0,6), {left: innerWidth/2-150, bottom: 100}, 0); };
})();
